// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Any?

  init(code: String, message: String?, details: Any?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
      }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

/// Availability of Apple's on-device Foundation Models framework. Mirrors
/// `SystemLanguageModel.Availability` on the Swift side. `notEligible`,
/// `notEnabled`, and `notReady` map to `SystemLanguageModel.Availability
/// .unavailable(reason:)`'s three cases — kept distinct so the UI can give
/// the right nudge (turn on Apple Intelligence vs. wait for it to download).
enum FoundationModelAvailability: Int {
  case available = 0
  case notEligibleDevice = 1
  case notEnabled = 2
  case modelNotReady = 3
  case unsupportedOS = 4
}

private class FoundationModelApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return FoundationModelAvailability(rawValue: enumResultAsInt)
      }
      return nil
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class FoundationModelApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? FoundationModelAvailability {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else {
      super.writeValue(value)
    }
  }
}

private class FoundationModelApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return FoundationModelApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return FoundationModelApiPigeonCodecWriter(data: data)
  }
}

class FoundationModelApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = FoundationModelApiPigeonCodec(readerWriter: FoundationModelApiPigeonCodecReaderWriter())
}


/// Generated from this schema via:
///   dart run pigeon --input pigeons/foundation_model.dart
/// Re-run that after editing this file — do not hand-edit the .g. outputs.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol FoundationModelHostApi {
  /// Cheap synchronous check — call before showing any AI-powered UI.
  func checkAvailability() throws -> FoundationModelAvailability
  /// Starts (or restarts) a session with the given system instructions.
  /// Throws a PlatformException if Foundation Models isn't available.
  func initializeSession(instructions: String, completion: @escaping (Result<Void, Error>) -> Void)
  /// Sends a prompt through the current session and returns the full
  /// response. Call `initializeSession` first.
  func generateResponse(prompt: String, completion: @escaping (Result<String, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class FoundationModelHostApiSetup {
  static var codec: FlutterStandardMessageCodec { FoundationModelApiPigeonCodec.shared }
  /// Sets up an instance of `FoundationModelHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: FoundationModelHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Cheap synchronous check — call before showing any AI-powered UI.
    let checkAvailabilityChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.copypasta.FoundationModelHostApi.checkAvailability\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      checkAvailabilityChannel.setMessageHandler { _, reply in
        do {
          let result = try api.checkAvailability()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      checkAvailabilityChannel.setMessageHandler(nil)
    }
    /// Starts (or restarts) a session with the given system instructions.
    /// Throws a PlatformException if Foundation Models isn't available.
    let initializeSessionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.copypasta.FoundationModelHostApi.initializeSession\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      initializeSessionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let instructionsArg = args[0] as! String
        api.initializeSession(instructions: instructionsArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      initializeSessionChannel.setMessageHandler(nil)
    }
    /// Sends a prompt through the current session and returns the full
    /// response. Call `initializeSession` first.
    let generateResponseChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.copypasta.FoundationModelHostApi.generateResponse\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      generateResponseChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let promptArg = args[0] as! String
        api.generateResponse(prompt: promptArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      generateResponseChannel.setMessageHandler(nil)
    }
  }
}
